paths:
  /api/products:
      get:
        summary: Obtiene la lista total de productos
        tags:
          - Products 
        responses:
          "200":
            description: Los productos fueron consultados correctamente
          "500":
            description: No se pudo entregar la información
      post:
        summary: Crea un nuevo producto
        tags:
          - Products 
        responses:
          "200":
            description: El producto fue creado correctamente
          "500":
            description: No se pudo entregar la información
  /api/products/{ProductId}:
      get:
        summary: Obtiene un producto en particular
        tags:
          - Products 
        responses:
          "200":
            description: El producto fue consultado correctamente
          "404":
            description: No se pudo entregar la información para este ProductId
          "500":
            description: No se pudo entregar la información 
      put:
        summary: Actualiza un producto en particular
        tags:
          - Products 
        responses:
          "200":
            description: El producto fue consultado correctamente
          "404":
            description: No se pudo entregar la información para este ProductId
          "400":
            description: envio de información errada
          "500":
            description: No se pudo entregar la información 
      delete:
        summary: Elimina un producto en particular
        tags:
          - Products 
        responses:
          "200": 
            description: El producto fue consultado correctamente
          "404":
            description: No se pudo entregar la información para este ProductId
          "500":
            description: No se pudo entregar la información
  # /api/products/mockingProducts:
  #     get:
  #       summary: Crea 100 productos para testear el funcionamiento de rutas y base de datos
  #       tags:
  #         - Products 
  #       responses:
  #         "200":
  #           description: Los productos se crearon perfectamente
  #         "500":
  #           description: No se pudo entregar la información 
components:
  schemas:
    products:
      type: object
      properties:
        _id:
          type: ObjectId
          decription: autogenerado de mongo
        title:
          type: String
          decription: Nombre del producto
        description:
          type: String
          decription: descripción del producto
        price:
          type: Number
          decription: Precio del producto
        code:
          type: String
          decription: Código del producto
        status:
          type: Boolean
          decription: Activo o no activo el producto
        stock:
          type: Number
          decription: Cantidad de stock del producto
        category:
          type: String
          decription: Categoria del producto
        owner:
          type: String
          decription: email del creador del productor